# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
