# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profile_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
