# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 09:34
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=162)),
                ('photo', models.ImageField(blank=True, upload_to='modelimages/')),
                ('author', models.CharField(max_length=162)),
                ('published', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catagories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=42)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='catagory_name', unique_with=['catagory_name'])),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='catagory',
            field=models.ForeignKey(on_delete=models.SET(1), to='books.Catagories'),
        ),
    ]
