# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20171101_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=162)),
                ('bookid', models.CharField(max_length=162)),
                ('collected', models.BooleanField(default=False)),
            ],
        ),
    ]
