# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 06:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20171102_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, default='settings.MEDIA_ROOT/files/book.pdf', upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 2, 6, 4, 7, 338920)),
        ),
    ]
