# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 07:06
from __future__ import unicode_literals

import datetime
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20171102_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, default='/files/book.pdf', storage=django.core.files.storage.FileSystemStorage(location='/home/sayone/akhil/sample/library/img'), upload_to='files'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 3, 7, 6, 33, 827940)),
        ),
    ]
