# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 09:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20171103_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 3, 9, 1, 55, 502709)),
        ),
    ]
