# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 11:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20171103_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 3, 11, 38, 38, 685297)),
        ),
    ]
