# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-11 06:03
from __future__ import unicode_literals

import datetime
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20171103_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf',
            field=models.FileField(blank=True, default='/files/book.pdf', storage=django.core.files.storage.FileSystemStorage(location='/home/akhil/akhil/samples/library/img'), upload_to='files'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 6, 3, 21, 374265)),
        ),
    ]
