# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-11 08:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20191111_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='test',
            field=models.ManyToManyField(blank=True, related_name='_book_test_+', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 8, 46, 50, 714313)),
        ),
    ]
