# Generated by Django 3.0.2 on 2020-02-20 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20191111_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='test',
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 9, 42, 17, 214735)),
        ),
    ]
