# Generated by Django 3.0.2 on 2020-02-20 09:44

import datetime
from django.db import migrations, models
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20200220_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author1',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=162, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description1',
            field=fernet_fields.fields.EncryptedTextField(blank=True, max_length=6000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='name1',
            field=fernet_fields.fields.EncryptedCharField(blank=True, max_length=162, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 9, 44, 57, 1498)),
        ),
    ]
